# Generated by Django 4.1.2 on 2023-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_reg_num', models.TextField(unique=True)),
                ('stu_name', models.TextField()),
                ('email', models.TextField()),
                ('stu_mob', models.TextField(null=True)),
                ('password', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
